services:
  nekuvio:
    image: nekuvio:${IMAGE_TAG:-dev}
    container_name: nekuvio
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "${PORT:-7000}:7000"

    environment:
      PORT: 7000
      NODE_ENV: production

    restart: unless-stopped
