#!/usr/bin/env python3

"""
Generate nekoBT metadata integration files.

This script is intentionally completely offline.

The nekoBT wiki is the HUMAN source of truth for the hardcoded metadata
definitions below. When nekoBT changes its metadata, manually update
NEKOBT_METADATA after checking:

    https://wiki.nekobt.to/info/metadata/
    https://wiki.nekobt.to/info/sub-levels/

Generated files:

    src/generated/nekobt-metadata.ts
    nuvio/nekobt-badges.json
    badges/**/*.{svg,png}

The generated TypeScript intentionally contains NO human-readable nekoBT
metadata. It only contains the protocol definition and generic encoding
functions.

All badges are regenerated on every run. Output files are only rewritten
when their generated bytes differ from the existing file.

Badge generation requires:

    pip install fonttools uharfbuzz

If BADGE_FORMAT is "png", CairoSVG is also required:

    pip install cairosvg
"""

from __future__ import annotations

import argparse
import json
from io import BytesIO
import math
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Callable

from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont


# =============================================================================
# Paths
# =============================================================================

ROOT = Path(__file__).resolve().parents[1]

TS_OUTPUT = ROOT / "src" / "generated" / "nekobt-metadata.ts"
NUVIO_OUTPUT = ROOT / "nuvio" / "nekobt-badges.json"
BADGES_DIR = ROOT / "badges"


# =============================================================================
# Generator configuration
# =============================================================================

# Change this to wherever the badge assets are hosted.
BADGE_BASE_URL = "https://raw.githubusercontent.com/dormindev/Nekuvio/refs/heads/development/badges"

# Currently only SVG is generated.
BADGE_FORMAT = "svg"


# =============================================================================
# Badge appearance
# =============================================================================

# The exact local Ubuntu Bold font is used only at generation time.
# Its glyph outlines are converted directly into SVG paths, so the generated
# badges do not contain a font dependency.
SVG_FONT_SIZE = 24

# Optional explicit path to the locally installed Ubuntu Bold font.
SVG_FONT_PATH: Path | None = None

UBUNTU_FONT_CANDIDATES = (
    Path("/usr/share/fonts/truetype/ubuntu/Ubuntu-B.ttf"),
    Path("/usr/share/fonts/truetype/ubuntu-font-family/Ubuntu-B.ttf"),
    Path("/usr/share/fonts/truetype/ubuntu/Ubuntu-Bold.ttf"),
    Path("/usr/local/share/fonts/Ubuntu-B.ttf"),
    Path("/usr/local/share/fonts/ubuntu/Ubuntu-B.ttf"),
    Path.home() / ".local/share/fonts/Ubuntu-B.ttf",
    Path.home() / ".local/share/fonts/ubuntu/Ubuntu-B.ttf",
)

SVG_BACKGROUND = "#00000000"
SVG_TEXT_COLOR = "#FFECF9FF"
SVG_BORDER_COLOR = "#00000000"

SVG_PADDING_X = 10
SVG_HEIGHT = SVG_FONT_SIZE+8
SVG_MIN_WIDTH = 0
SVG_BORDER_RADIUS = 8
SVG_BORDER_WIDTH = 2


# =============================================================================
# Nuvio defaults
# =============================================================================

DEFAULT_NUVIO = {
    "isEnabled": True,
    "tagColor": "#FF1A1A1A",
    "textColor": "#FFECF9FF",
    "borderColor": "#FF1A1A1A",
    "tagStyle": "filled",
    "type": "filter",
}


# =============================================================================
# Protocol
# =============================================================================

# Base-4 alphabet:
#
#   0 = FUNCTION APPLICATION
#   1 = INVISIBLE TIMES
#   2 = INVISIBLE SEPARATOR
#   3 = INVISIBLE PLUS
#
# All four characters are invisible Unicode characters.

BASE4_CHARS = (
    "\u2061",
    "\u2062",
    "\u2063",
    "\u2064",
)

START = "\u2060"
END = "\u034f"

PROTOCOL_VERSION = 0

MAGIC = 78
MAGIC_WIDTH = 4

VERSION_WIDTH = 2
FIELD_ID_WIDTH = 2


# =============================================================================
# Field configuration
# =============================================================================
#
# This is the protocol-facing definition of the fields.
#
# "metadata_key" points at the human-readable metadata below and is only used
# by the Python generator. It is NOT emitted into TypeScript.
#
# width = 0 means boolean/presence-only.
# width > 0 means numeric and specifies the base-4 payload width.
#
# The protocol field IDs are:
#
#   1 = sub level
#   2 = MTL
#   3 = OTL
#   4 = Hardsubs
#   5 = Video Type
#   6 = Video Codec
#   7 = Batch
# =============================================================================

@dataclass(frozen=True)
class FieldConfig:
    ts_name: str
    field_id: int
    width: int

    metadata_key: str
    metadata_section: str

    group_id: str
    badge_directory: str

    label: Callable[[dict[str, Any]], str]
    badge_filename: Callable[[dict[str, Any]], str]

    nuvio: dict[str, Any]


FIELD_CONFIG: tuple[FieldConfig, ...] = (
    FieldConfig(
        ts_name="subLevel",
        field_id=1,
        width=2,
        metadata_key="level",
        metadata_section="numeric",
        group_id="nekobt-sub-level",
        badge_directory="sub-level",
        label=lambda value: value["description"],
        badge_filename=lambda value: str(value["id"]),
        nuvio={
            "isEnabled": True,
            "textColor": "#FFECF9FF",
            "tagStyle": "filled",
            "type": "filter",
        },
    ),
    FieldConfig(
        ts_name="mtl",
        field_id=2,
        width=0,
        metadata_key="mtl",
        metadata_section="boolean",
        group_id="nekobt-translation",
        badge_directory="translation",
        label=lambda value: "MTL",
        badge_filename=lambda value: "mtl",
        nuvio={
            "isEnabled": True,
            "tagColor": "#FFFF6266",
            "textColor": "#FFECF9FF",
            "borderColor": "#FFFF6266",
            "tagStyle": "filled",
            "type": "filter",
        },
    ),
    FieldConfig(
        ts_name="otl",
        field_id=3,
        width=0,
        metadata_key="otl",
        metadata_section="boolean",
        group_id="nekobt-translation",
        badge_directory="translation",
        label=lambda value: "OTL",
        badge_filename=lambda value: "otl",
        nuvio={
            "isEnabled": True,
            "tagColor": "#FF00A63E",
            "textColor": "#FFECF9FF",
            "borderColor": "#FF00A63E",
            "tagStyle": "filled",
            "type": "filter",
        },
    ),
    FieldConfig(
        ts_name="hardsubs",
        field_id=4,
        width=0,
        metadata_key="hardsub",
        metadata_section="boolean",
        group_id="nekobt-hardsubs",
        badge_directory="hardsubs",
        label=lambda value: "Hardsub",
        badge_filename=lambda value: "hardsub",
        nuvio={
            "isEnabled": True,
            "tagColor": "#FFFF6266",
            "textColor": "#FFECF9FF",
            "borderColor": "#FFFF6266",
            "tagStyle": "filled",
            "type": "filter",
        },
    ),
    FieldConfig(
        ts_name="videoType",
        field_id=5,
        width=3,
        metadata_key="video_type",
        metadata_section="numeric",
        group_id="nekobt-video-type",
        badge_directory="video-type",
        label=lambda value: value["description"],
        badge_filename=lambda value: str(value["id"]),
        nuvio={
            "isEnabled": True,
            "tagColor": "#FF00A4F2",
            "textColor": "#FFECF9FF",
            "borderColor": "#FF00A4F2",
            "tagStyle": "filled",
            "type": "filter",
        },
    ),
    FieldConfig(
        ts_name="videoCodec",
        field_id=6,
        width=2,
        metadata_key="video_codec",
        metadata_section="numeric",
        group_id="nekobt-video-codec",
        badge_directory="video-codec",
        label=lambda value: value["description"],
        badge_filename=lambda value: str(value["id"]),
        nuvio={
            "isEnabled": True,
            "tagColor": "#FF00A4F2",
            "textColor": "#FFECF9FF",
            "borderColor": "#FF00A4F2",
            "tagStyle": "filled",
            "type": "filter",
        },
    ),
    FieldConfig(
        ts_name="batch",
        field_id=7,
        width=0,
        metadata_key="batch",
        metadata_section="boolean",
        group_id="nekobt-batch",
        badge_directory="batch",
        label=lambda value: "Batch",
        badge_filename=lambda value: "batch",
        nuvio={
            "isEnabled": True,
            "tagColor": "#FF0D542B",
            "textColor": "#FFECF9FF",
            "borderColor": "#FF0D542B",
            "tagStyle": "filled",
            "type": "filter",
        },
    ),
)


# =============================================================================
# nekoBT metadata
# =============================================================================
#
# This is deliberately hardcoded.
#
# Last manually checked:
#
#   2026-09-29
#
# Source:
#
#   https://wiki.nekobt.to/info/metadata/
#   https://wiki.nekobt.to/info/sub-levels/
#
# Do NOT turn this into a runtime web scraper.
#
# Update this block manually when the wiki changes.
# =============================================================================

NEKOBT_METADATA_LAST_CHECKED = "2026-09-29"

NEKOBT_METADATA: dict[str, Any] = {
    "level": {
        # -1 means "no sub-level".
        -1: {
            "id": -1,
            "description": None,
        },
        0: {
            "id": 0,
            "description": "L0 - Official",
            "nuvio": {
                "tagColor": "#FF3D434A",
                "borderColor": "#FF3D434A",
            },
        },
        1: {
            "id": 1,
            "description": "L1 - Slight",
            "nuvio": {
                "tagColor": "#FF7D7699",
                "borderColor": "#FF7D7699",
            },
        },
        2: {
            "id": 2,
            "description": "L2 - Small",
            "nuvio": {
                "tagColor": "#FF937AD7",
                "borderColor": "#FF937AD7",
            },
        },
        3: {
            "id": 3,
            "description": "L3 - Full",
            "nuvio": {
                "tagColor": "#FF8C4FFF",
                "borderColor": "#FF8C4FFF",
            },
        },
    },

    "video_type": {
        0: {
            "id": 0,
            "description": "Other",
        },
        1: {
            "id": 1,
            "description": "VHS",
        },
        2: {
            "id": 2,
            "description": "LaserDisc",
        },
        3: {
            "id": 3,
            "description": "TV - Encode",
        },
        4: {
            "id": 4,
            "description": "TV - Raw",
        },
        5: {
            "id": 5,
            "description": "DVD - Remux",
        },
        6: {
            "id": 6,
            "description": "DVD - Encode",
        },
        7: {
            "id": 7,
            "description": "WEB - Mini",
        },
        8: {
            "id": 8,
            "description": "WEB - Encode",
        },
        9: {
            "id": 9,
            "description": "WEB-DL",
        },
        11: {
            "id": 11,
            "description": "BD - Disc",
        },
        12: {
            "id": 12,
            "description": "BD - Mini",
        },
        13: {
            "id": 13,
            "description": "BD - Encode",
        },
        14: {
            "id": 14,
            "description": "BD - Remux",
        },
        15: {
            "id": 15,
            "description": "Hybrid",
        },
        16: {
            "id": 16,
            "description": "DVD - Disc",
        },
    },

    "video_codec": {
        0: {
            "id": 0,
            "description": "Other",
        },
        1: {
            "id": 1,
            "description": "H264",
        },
        2: {
            "id": 2,
            "description": "H265",
        },
        3: {
            "id": 3,
            "description": "AV1",
        },
        4: {
            "id": 4,
            "description": "VP9",
        },
        5: {
            "id": 5,
            "description": "MPEG-2",
        },
        6: {
            "id": 6,
            "description": "MPEG-4",
        },
        7: {
            "id": 7,
            "description": "WMV",
        },
        8: {
            "id": 8,
            "description": "VC1",
        },
    },

    "boolean": {
        "mtl": {
            "id": True,
            "description": "MTL",
        },
        "otl": {
            "id": True,
            "description": "OTL",
        },
        "hardsub": {
            "id": True,
            "description": "Hardsub",
        },
        "batch": {
            "id": True,
            "description": "Batch",
        },
    },
}


# =============================================================================
# Helpers
# =============================================================================

def base4_encode(value: int, width: int) -> str:
    """Encode an integer as exactly `width` invisible base-4 characters."""

    if not isinstance(value, int):
        raise TypeError(
            f"value must be int, got {type(value).__name__}"
        )

    if value < 0:
        raise ValueError("value must be >= 0")

    maximum = (4 ** width) - 1

    if value > maximum:
        raise ValueError(
            f"value {value} does not fit in {width} base-4 characters "
            f"(maximum {maximum})"
        )

    result: list[str] = []

    for shift in range(width - 1, -1, -1):
        digit = (value // (4 ** shift)) % 4
        result.append(BASE4_CHARS[digit])

    return "".join(result)


def xml_escape(value: str) -> str:
    return (
        value
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
        .replace("'", "&apos;")
    )


def ts_string(value: str) -> str:
    """
    Encode a string for TypeScript source.

    ensure_ascii=True is intentional: invisible Unicode characters must appear
    as escaped Unicode sequences such as "\\u2060", not as literal characters.
    """
    return json.dumps(
        value,
        ensure_ascii=True,
    )


def ts_identifier(value: str) -> str:
    parts = re.split(r"[^A-Za-z0-9]+", value)

    if not parts:
        return "field"

    result = parts[0]

    for part in parts[1:]:
        if part:
            result += part[:1].upper() + part[1:]

    if not result:
        result = "field"

    if result[0].isdigit():
        result = "_" + result

    return result


def make_image_url(
    directory: str,
    filename: str,
) -> str:
    return (
        f"{BADGE_BASE_URL.rstrip('/')}/"
        f"{directory}/{filename}"
    )


# =============================================================================
# Validation
# =============================================================================

def validate_metadata() -> None:
    required_sections = {
        "level",
        "video_type",
        "video_codec",
        "boolean",
    }

    missing = required_sections - NEKOBT_METADATA.keys()

    if missing:
        raise RuntimeError(
            f"Missing metadata sections: {sorted(missing)}"
        )

    field_ids = [
        field.field_id
        for field in FIELD_CONFIG
    ]

    if len(field_ids) != len(set(field_ids)):
        raise RuntimeError("Duplicate protocol field IDs")

    if len(BASE4_CHARS) != 4:
        raise RuntimeError(
            "Base-4 alphabet must contain exactly four characters"
        )

    if len(set(BASE4_CHARS)) != 4:
        raise RuntimeError(
            "Base-4 alphabet contains duplicate characters"
        )

    if len(START) != 1:
        raise RuntimeError("START must be exactly one character")

    if len(END) != 1:
        raise RuntimeError("END must be exactly one character")

    if START == END:
        raise RuntimeError("START and END must be different")

    if START in BASE4_CHARS:
        raise RuntimeError(
            "START must not be part of the base-4 alphabet"
        )

    if END in BASE4_CHARS:
        raise RuntimeError(
            "END must not be part of the base-4 alphabet"
        )

    if PROTOCOL_VERSION < 0:
        raise RuntimeError("Protocol version must be >= 0")

    if PROTOCOL_VERSION >= 4 ** VERSION_WIDTH:
        raise RuntimeError(
            "Protocol version does not fit in versionWidth"
        )

    if MAGIC < 0 or MAGIC >= 4 ** MAGIC_WIDTH:
        raise RuntimeError(
            "Magic value does not fit in magicWidth"
        )

    for field in FIELD_CONFIG:
        if field.field_id < 0:
            raise RuntimeError(
                f"{field.ts_name}: field ID must be >= 0"
            )

        if field.field_id >= 4 ** FIELD_ID_WIDTH:
            raise RuntimeError(
                f"{field.ts_name}: field ID {field.field_id} "
                f"does not fit in {FIELD_ID_WIDTH} base-4 characters"
            )

        if field.width < 0:
            raise RuntimeError(
                f"{field.ts_name}: width must be >= 0"
            )

        if field.metadata_section == "numeric":
            if field.metadata_key not in NEKOBT_METADATA:
                raise RuntimeError(
                    f"{field.ts_name}: missing metadata section "
                    f"{field.metadata_key!r}"
                )

            maximum = (4 ** field.width) - 1

            for value_id in NEKOBT_METADATA[field.metadata_key]:
                if (
                    field.ts_name == "subLevel"
                    and value_id == -1
                ):
                    continue

                if not isinstance(value_id, int):
                    raise RuntimeError(
                        f"{field.ts_name}: non-integer metadata ID "
                        f"{value_id!r}"
                    )

                if value_id < 0 or value_id > maximum:
                    raise RuntimeError(
                        f"{field.ts_name}: value {value_id} does not fit "
                        f"in {field.width} base-4 characters "
                        f"(maximum {maximum})"
                    )

        elif field.metadata_section == "boolean":
            if field.metadata_key not in NEKOBT_METADATA["boolean"]:
                raise RuntimeError(
                    f"{field.ts_name}: missing boolean metadata"
                )

        else:
            raise RuntimeError(
                f"{field.ts_name}: unsupported metadata section "
                f"{field.metadata_section!r}"
            )


def validate_marker_uniqueness() -> None:
    """
    Validate that every generated badge marker is unique.
    """

    markers: dict[str, str] = {}

    for field in FIELD_CONFIG:
        if field.metadata_section == "numeric":
            values = NEKOBT_METADATA[field.metadata_key]

            for value_id, value in values.items():
                if field.ts_name == "subLevel" and value_id == -1:
                    continue

                payload = (
                    base4_encode(
                        field.field_id,
                        FIELD_ID_WIDTH,
                    )
                    + base4_encode(
                        value_id,
                        field.width,
                    )
                )

                marker = make_marker(payload)

                description = (
                    f"{field.ts_name}={value_id}"
                )

                previous = markers.get(marker)

                if previous is not None:
                    raise RuntimeError(
                        f"Marker collision: {description} and {previous}"
                    )

                markers[marker] = description

        else:
            payload = base4_encode(
                field.field_id,
                FIELD_ID_WIDTH,
            )

            marker = make_marker(payload)

            description = field.ts_name

            previous = markers.get(marker)

            if previous is not None:
                raise RuntimeError(
                    f"Marker collision: {description} and {previous}"
                )

            markers[marker] = description

    print(
        f"Validated {len(markers)} unique invisible markers."
    )


# =============================================================================
# Invisible protocol marker generation
# =============================================================================

def make_marker(payload: str) -> str:
    """
    Construct a complete invisible protocol marker from an already-encoded
    payload.

        START + MAGIC + VERSION + PAYLOAD + END
    """

    return (
        START
        + base4_encode(MAGIC, MAGIC_WIDTH)
        + base4_encode(PROTOCOL_VERSION, VERSION_WIDTH)
        + payload
        + END
    )


# =============================================================================
# Font and SVG generation
# =============================================================================

def find_ubuntu_font() -> Path:
    for path in UBUNTU_FONT_CANDIDATES:
        if path.is_file():
            return path

    raise RuntimeError(
        "Ubuntu Bold font not found. "
        "Install Ubuntu Bold or pass its path with --font."
    )


def get_font_path(
    cli_path: Path | None,
) -> Path:
    if cli_path is not None:
        if not cli_path.is_file():
            raise RuntimeError(
                f"Configured font does not exist: {cli_path}"
            )

        return cli_path

    if SVG_FONT_PATH is not None:
        if not SVG_FONT_PATH.is_file():
            raise RuntimeError(
                f"Configured font does not exist: {SVG_FONT_PATH}"
            )

        return SVG_FONT_PATH

    return find_ubuntu_font()


@dataclass(frozen=True)
class BadgeFont:
    """Font data used to shape text and draw glyph outlines."""

    font: TTFont
    hb_font: Any
    glyph_set: Any
    glyph_order: tuple[str, ...]
    units_per_em: int
    supported_codepoints: frozenset[int]


def instantiate_bold_font(font: TTFont) -> TTFont:
    """
    Return a static Bold instance of the supplied font.

    Ubuntu on current Linux distributions is commonly installed as a single
    variable font with wght/wdth axes. The default instance is Regular, so
    checking OS/2.usWeightClass on the variable font itself is not sufficient.

    We pin wght to 700 (Bold) and every other variation axis to its default.
    """

    if "fvar" not in font:
        weight_class = None
        if "OS/2" in font:
            weight_class = font["OS/2"].usWeightClass

        if weight_class != 700:
            raise RuntimeError(
                "The supplied font is not Ubuntu Bold: "
                f"{font['name'].getDebugName(1)!r}, "
                f"weight={weight_class}"
            )

        return font

    axes = list(font["fvar"].axes)

    location: dict[str, float] = {}

    for axis in axes:
        if axis.axisTag == "wght":
            if not (
                axis.minValue <= 700 <= axis.maxValue
            ):
                raise RuntimeError(
                    "The supplied variable font does not support "
                    f"wght=700 (range {axis.minValue}..{axis.maxValue})."
                )

            location[axis.axisTag] = 700
        else:
            location[axis.axisTag] = axis.defaultValue

    if "wght" not in location:
        raise RuntimeError(
            "The supplied variable font has no 'wght' axis; "
            "cannot select Ubuntu Bold."
        )

    return instantiateVariableFont(
        font,
        location,
        inplace=False,
        updateFontNames=True,
        static=True,
    )


def load_badge_font(
    font_path: Path,
) -> BadgeFont:
    """Load the exact font file and instantiate its Bold face."""

    try:
        import uharfbuzz as hb
    except ImportError as exc:
        raise RuntimeError(
            "Badge generation requires uharfbuzz. "
            "Install it with: pip install uharfbuzz"
        ) from exc

    try:
        font = TTFont(str(font_path))
    except Exception as exc:
        raise RuntimeError(
            f"Failed to read font file: {font_path}"
        ) from exc

    family_name = font["name"].getDebugName(1) or ""
    full_name = font["name"].getDebugName(4) or ""

    if "Ubuntu" not in family_name and "Ubuntu" not in full_name:
        font.close()
        raise RuntimeError(
            f"Font is not an Ubuntu font: {font_path} "
            f"(family={family_name!r}, full={full_name!r})"
        )

    try:
        font = instantiate_bold_font(font)
    except Exception:
        font.close()
        raise

    weight_class = None
    if "OS/2" in font:
        weight_class = font["OS/2"].usWeightClass

    if weight_class != 700:
        font.close()
        raise RuntimeError(
            "Failed to create Ubuntu Bold instance from "
            f"{font_path}: weight={weight_class}"
        )

    font_bytes_io = BytesIO()
    font.save(font_bytes_io)
    font_bytes = font_bytes_io.getvalue()

    face = hb.Face(font_bytes)
    hb_font = hb.Font(face)

    units_per_em = font["head"].unitsPerEm
    hb_font.scale = (units_per_em, units_per_em)

    cmap: set[int] = set()
    for table in font["cmap"].tables:
        cmap.update(table.cmap.keys())

    return BadgeFont(
        font=font,
        hb_font=hb_font,
        glyph_set=font.getGlyphSet(),
        glyph_order=tuple(font.getGlyphOrder()),
        units_per_em=units_per_em,
        supported_codepoints=frozenset(cmap),
    )

def validate_text_glyphs(
    text: str,
    font: BadgeFont,
) -> None:
    missing = sorted(
        {
            ord(char)
            for char in text
            if ord(char) not in font.supported_codepoints
        }
    )

    if missing:
        characters = ", ".join(
            repr(chr(codepoint))
            for codepoint in missing
        )

        raise RuntimeError(
            f"Ubuntu Bold font is missing glyphs for: {characters}"
        )


def shape_text(
    text: str,
    font: BadgeFont,
) -> tuple[list[Any], list[Any]]:
    """Shape text with HarfBuzz using the exact supplied font."""

    import uharfbuzz as hb

    buffer = hb.Buffer()
    buffer.add_str(text)
    buffer.guess_segment_properties()

    hb.shape(
        font.hb_font,
        buffer,
        {
            "kern": True,
            "liga": True,
        },
    )

    return buffer.glyph_infos, buffer.glyph_positions


def get_shaped_bounds(
    font: BadgeFont,
    glyph_infos: list[Any],
    glyph_positions: list[Any],
) -> tuple[float, float, float, float, float]:
    """
    Return shaped text bounds and total advance in font units.

    The returned values are:

        min_x, min_y, max_x, max_y, total_x_advance
    """

    cursor_x = 0.0
    cursor_y = 0.0

    min_x: float | None = None
    min_y: float | None = None
    max_x: float | None = None
    max_y: float | None = None

    for info, position in zip(glyph_infos, glyph_positions):
        glyph_id = info.codepoint

        if glyph_id < 0 or glyph_id >= len(font.glyph_order):
            raise RuntimeError(
                f"HarfBuzz returned invalid glyph ID {glyph_id}"
            )

        glyph_name = font.glyph_order[glyph_id]
        glyph = font.glyph_set[glyph_name]

        glyph_x = cursor_x + position.x_offset
        glyph_y = cursor_y + position.y_offset

        bounds_pen = BoundsPen(font.glyph_set)
        glyph.draw(bounds_pen)

        if bounds_pen.bounds is not None:
            glyph_min_x, glyph_min_y, glyph_max_x, glyph_max_y = (
                bounds_pen.bounds
            )

            glyph_min_x += glyph_x
            glyph_max_x += glyph_x
            glyph_min_y += glyph_y
            glyph_max_y += glyph_y

            min_x = (
                glyph_min_x
                if min_x is None
                else min(min_x, glyph_min_x)
            )
            min_y = (
                glyph_min_y
                if min_y is None
                else min(min_y, glyph_min_y)
            )
            max_x = (
                glyph_max_x
                if max_x is None
                else max(max_x, glyph_max_x)
            )
            max_y = (
                glyph_max_y
                if max_y is None
                else max(max_y, glyph_max_y)
            )

        cursor_x += position.x_advance
        cursor_y += position.y_advance

    if min_x is None:
        min_x = 0.0
        max_x = cursor_x
        min_y = 0.0
        max_y = 0.0

    max_x = max(max_x, cursor_x)

    return (
        min_x,
        min_y,
        max_x,
        max_y,
        cursor_x,
    )


def make_svg(
    text: str,
    font: BadgeFont,
) -> str:
    """Generate a font-independent SVG badge using actual glyph paths."""

    validate_text_glyphs(text, font)

    glyph_infos, glyph_positions = shape_text(
        text,
        font,
    )

    (
        min_x,
        min_y,
        max_x,
        max_y,
        _,
    ) = get_shaped_bounds(
        font,
        glyph_infos,
        glyph_positions,
    )

    scale = SVG_FONT_SIZE / font.units_per_em

    text_width = (max_x - min_x) * scale
    text_height = (max_y - min_y) * scale

    width = max(
        SVG_MIN_WIDTH,
        math.ceil(
            text_width + SVG_PADDING_X * 2
        ),
    )

    height = max(
        SVG_HEIGHT,
        math.ceil(text_height),
    )

    center_x = (min_x + max_x) / 2
    center_y = (min_y + max_y) / 2

    translate_x = (
        width / 2
        - center_x * scale
    )

    # Font coordinates are Y-up while SVG coordinates are Y-down.
    translate_y = (
        height / 2
        + center_y * scale
    )

    paths: list[str] = []

    cursor_x = 0.0
    cursor_y = 0.0

    for info, position in zip(glyph_infos, glyph_positions):
        glyph_id = info.codepoint
        glyph_name = font.glyph_order[glyph_id]
        glyph = font.glyph_set[glyph_name]

        pen = SVGPathPen(font.glyph_set)

        glyph_x = cursor_x + position.x_offset
        glyph_y = cursor_y + position.y_offset

        transform_pen = TransformPen(
            pen,
            (
                scale,
                0,
                0,
                -scale,
                translate_x + glyph_x * scale,
                translate_y + glyph_y * scale,
            ),
        )

        glyph.draw(transform_pen)

        path = pen.getCommands()

        if path:
            paths.append(path)

        cursor_x += position.x_advance
        cursor_y += position.y_advance

    path_elements = "\n".join(
        f'  <path d="{xml_escape(path)}" '
        f'fill="{SVG_TEXT_COLOR}"/>'
        for path in paths
    )

    return f'''<?xml version="1.0" encoding="UTF-8"?>
<svg
    xmlns="http://www.w3.org/2000/svg"
    width="{width}"
    height="{height}"
    viewBox="0 0 {width} {height}">
  <rect
      x="{SVG_BORDER_WIDTH / 2}"
      y="{SVG_BORDER_WIDTH / 2}"
      width="{width - SVG_BORDER_WIDTH}"
      height="{height - SVG_BORDER_WIDTH}"
      rx="{SVG_BORDER_RADIUS}"
      ry="{SVG_BORDER_RADIUS}"
      fill="{SVG_BACKGROUND}"
      stroke="{SVG_BORDER_COLOR}"
      stroke-width="{SVG_BORDER_WIDTH}"/>
{path_elements}
</svg>
'''


def write_badge(
    output: Path,
    label: str,
    font: BadgeFont,
) -> bool:
    """Regenerate the badge and write it only if its bytes changed."""

    svg = make_svg(
        label,
        font,
    )

    output.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    if BADGE_FORMAT == "svg":
        return write_if_changed(
            output,
            svg.encode("utf-8"),
        )

    if BADGE_FORMAT == "png":
        try:
            import cairosvg
        except ImportError as exc:
            raise RuntimeError(
                "PNG generation requires CairoSVG. "
                "Install it with: pip install cairosvg"
            ) from exc

        png = cairosvg.svg2png(
            bytestring=svg.encode("utf-8"),
            scale=2,
        )

        return write_if_changed(
            output,
            png,
        )

    raise RuntimeError(
        f"Unsupported BADGE_FORMAT: {BADGE_FORMAT!r}"
    )


# =============================================================================
# Nuvio JSON generation
# =============================================================================

def make_nuvio_filter(
    field: FieldConfig,
    value: dict[str, Any],
) -> dict[str, Any]:
    if field.width == 0:
        # Boolean/presence-only field.
        payload = base4_encode(
            field.field_id,
            FIELD_ID_WIDTH,
        )

        marker = make_marker(payload)

        badge_name = field.label(value)
        badge_filename = field.badge_filename(value)

        filter_suffix = "true"

    else:
        # Numeric field: field ID + field value.
        payload = (
            base4_encode(
                field.field_id,
                FIELD_ID_WIDTH,
            )
            + base4_encode(
                value["id"],
                field.width,
            )
        )

        marker = make_marker(payload)

        badge_name = field.label(value)
        badge_filename = field.badge_filename(value)

        filter_suffix = str(value["id"])

    config = dict(DEFAULT_NUVIO)
    config.update(field.nuvio)

    value_nuvio = value.get("nuvio")
    if value_nuvio:
        config.update(value_nuvio)

    result = {
        "id": f"nekobt-{field.ts_name}-{filter_suffix}",
        "groupId": field.group_id,
        "name": badge_name,
        "pattern": marker,
        "imageURL": make_image_url(
            field.badge_directory,
            f"{badge_filename}.{BADGE_FORMAT}",
        ),
    }

    result.update(config)

    return result

def generate_nuvio_json() -> dict[str, Any]:
    filters: list[dict[str, Any]] = []

    for field in FIELD_CONFIG:
        if field.metadata_section == "numeric":
            values = NEKOBT_METADATA[field.metadata_key]

            for value_id in sorted(values):
                # -1 means no sub-level and therefore no badge.
                if (
                    field.ts_name == "subLevel"
                    and value_id == -1
                ):
                    continue

                filters.append(
                    make_nuvio_filter(
                        field,
                        values[value_id],
                    )
                )

        elif field.metadata_section == "boolean":
            value = NEKOBT_METADATA["boolean"][field.metadata_key]

            filters.append(
                make_nuvio_filter(
                    field,
                    value,
                )
            )

    return {
        "filters": filters,
    }


# =============================================================================
# TypeScript generation
# =============================================================================

def generate_typescript() -> str:
    """
    Generate the minimal protocol-only TypeScript implementation.

    Human-readable metadata is deliberately not emitted.
    """

    lines: list[str] = [
        "// THIS FILE IS GENERATED.",
        "// DO NOT EDIT MANUALLY.",
        "",
        "",
        "export type NekobtMetadata = {",
        "  subLevel?: number | null;",
        "  mtl?: boolean | null;",
        "  otl?: boolean | null;",
        "  hardsubs?: boolean | null;",
        "  videoType?: number | null;",
        "  videoCodec?: number | null;",
        "  batch?: boolean | null;",
        "};",
        "",
        "const INVISIBLE_MARKERS = {",
        f"  start: {ts_string(START)},",
        f"  end: {ts_string(END)},",
        "  base4: [",
    ]

    for char in BASE4_CHARS:
        lines.append(
            f"    {ts_string(char)},"
        )

    lines.extend(
        [
            "  ],",
            "} as const;",
            "",
            "const NEKOBT_PROTOCOL = {",
            f"  version: {PROTOCOL_VERSION},",
            f"  magic: {MAGIC},",
            f"  magicWidth: {MAGIC_WIDTH},",
            f"  versionWidth: {VERSION_WIDTH},",
            f"  fieldIdWidth: {FIELD_ID_WIDTH},",
            "} as const;",
            "",
            "const NEKOBT_FIELDS = {",
        ]
    )

    for field in FIELD_CONFIG:
        lines.append(
            f"  {field.ts_name}: "
            f"{{ id: {field.field_id}, width: {field.width} }},"
        )

    lines.extend(
        [
            "} as const;",
            "",
            "type NekobtField =",
            "  (typeof NEKOBT_FIELDS)[keyof typeof NEKOBT_FIELDS];",
            "",
            "",
            "function encodeBase4(",
            "  value: number,",
            "  width: number,",
            "): string {",
            "  if (",
            "    !Number.isSafeInteger(value) ||",
            "    value < 0 ||",
            "    value >= 4 ** width",
            "  ) {",
            '    return "";',
            "  }",
            "",
            '  let result = "";',
            "",
            "  for (",
            "    let shift = width - 1;",
            "    shift >= 0;",
            "    shift--",
            "  ) {",
            "    const digit =",
            "      Math.floor(value / 4 ** shift) % 4;",
            "",
            "    result += INVISIBLE_MARKERS.base4[digit];",
            "  }",
            "",
            "  return result;",
            "}",
            "",
            "",
            "function encodeBadge(payload: string): string {",
            "  if (!payload) {",
            '    return "";',
            "  }",
            "",
            "  const magic = encodeBase4(",
            "    NEKOBT_PROTOCOL.magic,",
            "    NEKOBT_PROTOCOL.magicWidth,",
            "  );",
            "",
            "  const version = encodeBase4(",
            "    NEKOBT_PROTOCOL.version,",
            "    NEKOBT_PROTOCOL.versionWidth,",
            "  );",
            "",
            "  if (!magic || !version) {",
            '    return "";',
            "  }",
            "",
            "  return (",
            "    INVISIBLE_MARKERS.start +",
            "    magic +",
            "    version +",
            "    payload +",
            "    INVISIBLE_MARKERS.end",
            "  );",
            "}",
            "",
            "",
            "function encodeBooleanField(",
            "  fieldId: number,",
            "  value: unknown,",
            "): string {",
            "  if (value !== true) {",
            '    return "";',
            "  }",
            "",
            "  const payload = encodeBase4(",
            "    fieldId,",
            "    NEKOBT_PROTOCOL.fieldIdWidth,",
            "  );",
            "",
            "  return encodeBadge(payload);",
            "}",
            "",
            "",
            "function encodeNumericField(",
            "  fieldId: number,",
            "  value: unknown,",
            "  width: number,",
            "): string {",
            "  if (",
            "    typeof value !== \"number\" ||",
            "    !Number.isSafeInteger(value) ||",
            "    value < 0",
            "  ) {",
            '    return "";',
            "  }",
            "",
            "  const encodedFieldId = encodeBase4(",
            "    fieldId,",
            "    NEKOBT_PROTOCOL.fieldIdWidth,",
            "  );",
            "",
            "  const encodedValue = encodeBase4(",
            "    value,",
            "    width,",
            "  );",
            "",
            "  if (!encodedFieldId || !encodedValue) {",
            '    return "";',
            "  }",
            "",
            "  return encodeBadge(",
            "    encodedFieldId + encodedValue,",
            "  );",
            "}",
            "",
            "",
            "function encodeField(",
            "  field: NekobtField,",
            "  value: unknown,",
            "): string {",
            "  if (field.width === 0) {",
            "    return encodeBooleanField(",
            "      field.id,",
            "      value,",
            "    );",
            "  }",
            "",
            "  return encodeNumericField(",
            "    field.id,",
            "    value,",
            "    field.width,",
            "  );",
            "}",
            "",
            "",
            "export function encodeNekobtMetadata(",
            "  metadata: NekobtMetadata | null | undefined,",
            "): string {",
            "  if (!metadata) {",
            '    return "";',
            "  }",
            "",
            '  let result = "";',
            "",
            "  for (const [name, value] of Object.entries(metadata)) {",
            "    const field =",
            "      NEKOBT_FIELDS[",
            "        name as keyof typeof NEKOBT_FIELDS",
            "      ];",
            "",
            "    if (!field) {",
            "      continue;",
            "    }",
            "",
            "    // -1 means \"no sub-level\", so no badge is emitted.",
            "    if (",
            '      name === "subLevel" &&',
            "      value === -1",
            "    ) {",
            "      continue;",
            "    }",
            "",
            "    result += encodeField(field, value);",
            "  }",
            "",
            "  return result;",
            "}",
            "",
        ]
    )

    return "\n".join(lines)


# =============================================================================
# File output
# =============================================================================

def write_if_changed(
    path: Path,
    data: bytes,
) -> bool:
    """
    Write a file only when its contents differ.

    Returns True if the file was created or changed.
    """

    if path.exists() and path.read_bytes() == data:
        return False

    path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    path.write_bytes(data)
    return True


def write_text_file(
    path: Path,
    content: str,
) -> bool:
    return write_if_changed(
        path,
        content.encode("utf-8"),
    )


def write_json_file(
    path: Path,
    data: Any,
) -> bool:
    content = (
        json.dumps(
            data,
            ensure_ascii=True,
            indent=2,
        )
        + "\n"
    )

    return write_text_file(
        path,
        content,
    )

# =============================================================================
# Badge generation
# =============================================================================

def generate_badges(
    font: BadgeFont,
) -> tuple[int, int]:
    """
    Regenerate all badges.

    Returns:
        (changed, unchanged)
    """

    changed = 0
    unchanged = 0

    for field in FIELD_CONFIG:
        if field.metadata_section == "numeric":
            values = NEKOBT_METADATA[field.metadata_key]

            for value_id in sorted(values):
                # -1 means no sub-level and therefore no badge.
                if (
                    field.ts_name == "subLevel"
                    and value_id == -1
                ):
                    continue

                value = values[value_id]

                label = field.label(value)

                filename = (
                    f"{field.badge_filename(value)}"
                    f".{BADGE_FORMAT}"
                )

                output = (
                    BADGES_DIR
                    / field.badge_directory
                    / filename
                )

                if write_badge(
                    output,
                    label,
                    font,
                ):
                    changed += 1
                else:
                    unchanged += 1

        elif field.metadata_section == "boolean":
            value = NEKOBT_METADATA["boolean"][field.metadata_key]

            label = field.label(value)

            filename = (
                f"{field.badge_filename(value)}"
                f".{BADGE_FORMAT}"
            )

            output = (
                BADGES_DIR
                / field.badge_directory
                / filename
            )

            if write_badge(
                    output,
                    label,
                    font,
                ):
                changed += 1
            else:
                unchanged += 1

    return changed, unchanged


# =============================================================================
# Main
# =============================================================================

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate nekoBT metadata integration files."
    )

    parser.add_argument(
        "--font",
        type=Path,
        help="Path to the locally installed Ubuntu Bold TTF/OTF font.",
    )

    return parser.parse_args()


def main() -> int:
    print("Nekobt metadata generator")
    print("=========================")
    print(
        f"Last checked:     {NEKOBT_METADATA_LAST_CHECKED}"
    )
    print(
        f"Protocol version: {PROTOCOL_VERSION}"
    )
    print(
        f"Badge format:     {BADGE_FORMAT}"
    )
    print()

    validate_metadata()
    validate_marker_uniqueness()

    # -------------------------------------------------------------------------
    # Font
    # -------------------------------------------------------------------------

    args = parse_args()

    font_path = get_font_path(args.font)

    print(f"Font:             {font_path}")

    font = load_badge_font(font_path)

    print(
        f"Font instance: {font.font['name'].getDebugName(1)!r} "
        f"{font.font['name'].getDebugName(2)!r}, "
        f"weight={font.font['OS/2'].usWeightClass if 'OS/2' in font.font else None}"
    )

    # -------------------------------------------------------------------------
    # TypeScript
    # -------------------------------------------------------------------------

    typescript = generate_typescript()

    typescript_changed = write_text_file(TS_OUTPUT, typescript)

    print(f"TypeScript:   {'changed' if typescript_changed else 'unchanged'}")

    # -------------------------------------------------------------------------
    # Nuvio JSON
    # -------------------------------------------------------------------------

    nuvio = generate_nuvio_json()

    nuvio_changed = write_json_file(NUVIO_OUTPUT, nuvio)

    print(f"Nuvio JSON:   {'changed' if nuvio_changed else 'unchanged'}")

    # -------------------------------------------------------------------------
    # Badges
    # -------------------------------------------------------------------------

    changed, unchanged = generate_badges(font)

    print(f"Badges changed:       {changed}")
    print(f"Badges unchanged:     {unchanged}")

    print()
    print("Done.")

    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except KeyboardInterrupt:
        print("\nInterrupted.", file=sys.stderr)
        raise SystemExit(130)
    except Exception as exc:
        print(
            f"\nERROR: {exc}",
            file=sys.stderr,
        )
        raise SystemExit(1)